-- Insert comprehensive pre-use check items (function tests before public use)
INSERT INTO check_library_items (frequency, label, hint, risk_level, sort_index, is_active) VALUES
-- Essential Pre-Use Function Tests
('preuse', 'Complete test cycle run', 'Run full cycle with empty cars before public use', 'high', 1, true),
('preuse', 'Emergency stop (E-Stop) function test', 'Test all E-stops respond and halt ride immediately', 'high', 2, true),
('preuse', 'Safety gate interlock test', 'Verify ride cannot start with gates open', 'high', 3, true),
('preuse', 'Restraint lock verification', 'Test all restraints lock and release correctly', 'high', 4, true),
('preuse', 'Operator controls responsive', 'Test start/stop/speed controls function correctly', 'high', 5, true),
('preuse', 'Height restriction check', 'Confirm height measure in place and visible', 'med', 6, true),
('preuse', 'Capacity signage displayed', 'Maximum riders and weight limits visible', 'med', 7, true),
('preuse', 'Lighting and signals working', 'All warning lights and signals functional', 'med', 8, true),
('preuse', 'Audio announcements test', 'Safety announcements play correctly', 'med', 9, true),
('preuse', 'Perimeter barriers secure', 'All barriers in place and stable', 'high', 10, true),
('preuse', 'Exit pathway clear', 'Emergency exits unobstructed', 'high', 11, true),
('preuse', 'Operator competency confirmed', 'Trained operator present and ready', 'high', 12, true),
('preuse', 'Weather conditions acceptable', 'Wind/rain within operational limits', 'high', 13, true),
('preuse', 'Ground conditions stable', 'No water pooling or uneven surfaces', 'med', 14, true),
('preuse', 'First aid kit accessible', 'Kit stocked and within reach', 'med', 15, true),

-- Additional comprehensive daily items
('daily', 'Structural bolts visual check', 'Look for any loose or missing bolts', 'high', 50, true),
('daily', 'Hydraulic fluid levels', 'Check for leaks and proper levels', 'high', 51, true),
('daily', 'Electrical cable condition', 'No fraying, damage or exposed wires', 'high', 52, true),
('daily', 'Floor surface condition', 'No slippery surfaces or trip hazards', 'med', 53, true),
('daily', 'Handrails and grab bars secure', 'All handrails firmly attached', 'med', 54, true),
('daily', 'Step/platform condition', 'Steps stable, non-slip surfaces intact', 'med', 55, true),
('daily', 'Decorative elements secure', 'All theming/decorations firmly attached', 'low', 56, true),

-- More comprehensive monthly items (component-focused)
('monthly', 'Wheel bearings inspection', 'Listen for unusual noise, check for play', 'high', 50, true),
('monthly', 'Gearbox oil condition', 'Check oil level and quality', 'high', 51, true),
('monthly', 'Motor brush wear', 'Inspect electric motor brushes', 'high', 52, true),
('monthly', 'Brake pad thickness', 'Measure remaining pad material', 'high', 53, true),
('monthly', 'Pulley alignment check', 'Verify pulleys are aligned correctly', 'med', 54, true),
('monthly', 'Safety switch calibration', 'Test and calibrate safety sensors', 'high', 55, true),
('monthly', 'Restraint mechanism service', 'Lubricate and test all restraints', 'high', 56, true),
('monthly', 'Foundation bolt torque', 'Check anchor bolts are at spec', 'high', 57, true),
('monthly', 'Corrosion inspection', 'Check for rust/corrosion on metal parts', 'med', 58, true),
('monthly', 'Weld visual inspection', 'Look for cracks in weld joints', 'high', 59, true),
('monthly', 'Pneumatic system test', 'Check air pressure and seals', 'med', 60, true),
('monthly', 'Control wiring inspection', 'Check all control connections', 'high', 61, true),
('monthly', 'Seat upholstery condition', 'Check for tears or wear', 'low', 62, true),
('monthly', 'Paint and finish condition', 'Note areas needing touch-up', 'low', 63, true),

-- More comprehensive yearly items (major overhaul items)
('yearly', 'Full structural NDT recommended', 'Schedule non-destructive testing if due', 'high', 50, true),
('yearly', 'Complete bearing replacement review', 'Assess all bearings for replacement', 'high', 51, true),
('yearly', 'Gearbox oil change', 'Drain and replace gearbox oil', 'high', 52, true),
('yearly', 'All safety sensor recalibration', 'Full calibration of all sensors', 'high', 53, true),
('yearly', 'Electrical system test', 'Full electrical inspection and testing', 'high', 54, true),
('yearly', 'Foundation inspection', 'Check concrete/steel foundations', 'high', 55, true),
('yearly', 'Full repaint assessment', 'Assess need for complete repaint', 'low', 56, true),
('yearly', 'Manufacturer service bulletin review', 'Check for any safety bulletins', 'high', 57, true),
('yearly', 'Documentation audit', 'Verify all records are complete', 'med', 58, true),
('yearly', 'Staff training records review', 'Confirm all operators certified', 'med', 59, true),
('yearly', 'Insurance certificate renewal check', 'Verify insurance is current', 'high', 60, true),
('yearly', 'Emergency procedure drill', 'Conduct full emergency evacuation drill', 'high', 61, true),
('yearly', 'Complete restraint system overhaul', 'Full service of all restraints', 'high', 62, true),
('yearly', 'Control system software update', 'Check for and apply updates', 'med', 63, true),
('yearly', 'Major component wear measurement', 'Measure critical wear points', 'high', 64, true);