-- Add European and American ride categories for international showmen
-- Using ON CONFLICT to skip any that already exist

-- European Rides
INSERT INTO ride_categories (name, category_group, description) VALUES
('Tagada', 'Rides', 'Circular bouncing platform ride popular in Europe'),
('Breakdance', 'Rides', 'Spinning platform ride with rotating cars'),
('Music Express', 'Rides', 'Undulating track ride with spinning cars and music'),
('Ghost Train', 'Rides', 'Dark ride through horror-themed scenes'),
('Enterprise', 'Rides', 'Large wheel ride that tilts and spins'),
('Air Race', 'Rides', 'Aircraft-themed spinning thrill ride'),
('Top Spin', 'Rides', 'Gondola ride that flips end over end'),
('Crazy Mouse', 'Rides', 'Wild mouse style spinning roller coaster'),
('Bayern Kurve', 'Rides', 'Motorcycle-themed circular spinning ride'),
('Rotor', 'Rides', 'Centrifugal force wall-sticking ride'),
('Love Express', 'Rides', 'Heart-themed family spinning ride'),
('Caterpillar', 'Rides', 'Undulating track ride with retractable canopy'),
('Frisbee', 'Rides', 'Giant pendulum disc ride'),
('Ranger', 'Rides', 'Swinging and rotating ship ride'),
('Afterburner', 'Rides', 'Looping arm thrill ride'),
('Tilt-A-Whirl', 'Rides', 'Classic American spinning platform ride'),
('Scrambler', 'Rides', 'Spinning arm ride with whipping motion'),
('Gravitron', 'Rides', 'UFO-themed centrifugal force ride'),
('Zipper', 'Rides', 'Rotating cages on a moving arm'),
('Ring of Fire', 'Rides', 'Loop-the-loop circular track ride'),
('Sizzler', 'Rides', 'Multi-arm spinning platform ride'),
('Tempest', 'Rides', 'High-speed spinning arm ride'),
('Yo-Yo', 'Rides', 'Chair swing ride that tilts while spinning'),
('Paratrooper', 'Rides', 'Umbrella-themed tilting swing ride'),
('Round Up', 'Rides', 'Tilting centrifugal force platform ride'),
('Spider', 'Rides', 'Multi-arm ride with undulating motion'),
('Octopus', 'Rides', 'Eight-arm ride with rising and falling cars'),
('Rock-O-Plane', 'Rides', 'Ferris wheel with spinning cages'),
('Kamikaze', 'Rides', 'Swinging pendulum ship ride'),
('Super Shot', 'Rides', 'Drop tower thrill ride'),
('Funnel Cake', 'Food Stalls', 'Deep-fried batter cake with powdered sugar'),
('Corn Dog', 'Food Stalls', 'Battered hot dog on a stick'),
('Churros', 'Food Stalls', 'Fried dough pastry with cinnamon sugar'),
('Turkey Leg', 'Food Stalls', 'Smoked turkey leg stand'),
('Fried Dough', 'Food Stalls', 'Deep-fried dough with various toppings'),
('Lemonade Stand', 'Food Stalls', 'Fresh squeezed lemonade and drinks'),
('Kettle Corn', 'Food Stalls', 'Sweet and salty popcorn specialty'),
('Nachos Stand', 'Food Stalls', 'Nachos with cheese and toppings'),
('Pretzel Stand', 'Food Stalls', 'Soft pretzels and pretzel bites'),
('Bratwurst', 'Food Stalls', 'German sausage stand'),
('Currywurst', 'Food Stalls', 'German curry sausage specialty'),
('Waffle Stand', 'Food Stalls', 'Belgian waffles with toppings'),
('Crepes', 'Food Stalls', 'French-style thin pancakes'),
('Pommes Frites', 'Food Stalls', 'European-style chips/fries'),
('Döner Kebab', 'Food Stalls', 'Turkish-style kebab meat wrap'),
('Roasted Nuts', 'Food Stalls', 'Candied and roasted nuts'),
('Ring Toss', 'Games', 'Throw rings onto bottles or pegs'),
('Balloon Darts', 'Games', 'Pop balloons with darts to win prizes'),
('Basketball Shootout', 'Games', 'Shoot baskets to win prizes'),
('Water Gun Race', 'Games', 'Spray water to race horses or targets'),
('Duck Pond', 'Games', 'Pick floating ducks for prizes'),
('High Striker', 'Games', 'Hammer strength test game'),
('Bottle Stand', 'Games', 'Knock down bottles with balls'),
('Hook-A-Duck', 'Games', 'Hook floating ducks with a rod'),
('Coconut Shy', 'Games', 'Knock coconuts off stands with balls'),
('Shooting Gallery', 'Games', 'Air rifle or cork gun target game'),
('Whack-A-Mole', 'Games', 'Hit popping moles with mallet'),
('Spin the Wheel', 'Games', 'Wheel of fortune prize game'),
('Milk Bottle Toss', 'Games', 'Knock down stacked milk bottles'),
('Fishing Game', 'Games', 'Magnetic fishing for prizes'),
('Hoopla', 'Games', 'Throw hoops over prizes to win')
ON CONFLICT (name) DO NOTHING;