INSERT INTO public.audit_logs (
  user_id, action, resource_type, resource_id,
  details,
  before_data,
  after_data,
  changed_fields,
  organisation_name, equipment_name,
  result, context_hint, reason
) VALUES (
  '1faaf0c4-d8ec-4af2-a700-aadf9d763bc9',
  'update',
  'ride',
  gen_random_uuid(),
  '{"name":"Waltzer","source":"RideForm","module":"equipment-detail"}'::jsonb,
  '{"name":"Waltzr","status":"active","max_speed":"12 mph","location":"Zone A","last_inspection":"2026-01-15"}'::jsonb,
  '{"name":"Waltzer","status":"active","max_speed":"15 mph","location":"Zone B","last_inspection":"2026-01-15"}'::jsonb,
  ARRAY['name','max_speed','location'],
  'Knutsen Amusements',
  'Waltzer',
  'success',
  'Equipment detail page',
  'Corrected typo in name and updated operating limits after site move'
),
(
  '1faaf0c4-d8ec-4af2-a700-aadf9d763bc9',
  'close',
  'defect',
  gen_random_uuid(),
  '{"description":"Loose handrail bolt on entry steps","severity":"major","source":"DefectClosureDialog"}'::jsonb,
  '{"status":"open","severity":"major","description":"Loose handrail bolt on entry steps"}'::jsonb,
  '{"status":"closed","severity":"major","description":"Loose handrail bolt on entry steps","resolved_at":"2026-03-27T22:10:00Z"}'::jsonb,
  ARRAY['status'],
  'Knutsen Amusements',
  'Waltzer',
  'success',
  'Defect register',
  'Bolt replaced and torqued to spec. Confirmed by site engineer.'
),
(
  '1faaf0c4-d8ec-4af2-a700-aadf9d763bc9',
  'delete',
  'document',
  gen_random_uuid(),
  '{"document_name":"Old Insurance Certificate 2024.pdf","document_type":"Insurance Certificate","source":"GlobalDocumentView"}'::jsonb,
  '{"document_name":"Old Insurance Certificate 2024.pdf","document_type":"Insurance Certificate","expires_at":"2025-06-30","file_size":245000}'::jsonb,
  NULL,
  NULL,
  'Knutsen Amusements',
  'Waltzer',
  'success',
  'Document register',
  'Expired document removed during annual cleanup'
),
(
  '1faaf0c4-d8ec-4af2-a700-aadf9d763bc9',
  'grant',
  'support_access',
  gen_random_uuid(),
  '{"duration_hours":24,"source":"SupportAccessManager"}'::jsonb,
  NULL,
  '{"access_granted":true,"duration_hours":24,"expires_at":"2026-03-28T22:10:00Z"}'::jsonb,
  NULL,
  'Knutsen Amusements',
  NULL,
  'success',
  'Settings / Support Access',
  'Granted for billing query investigation'
);